
sglB070.o:     file format coff-sh


Disassembly of section SLPROG:

00000000 <_slScrPosNbg0>:
   0:	60 43       	mov	r4,r0
   2:	c2 4c       	mov.l	r0,@(304,gbr)
   4:	60 53       	mov	r5,r0
   6:	00 0b       	rts	
   8:	c2 4d       	mov.l	r0,@(308,gbr)

0000000a <_slScrPosNbg1>:
   a:	60 43       	mov	r4,r0
   c:	c2 50       	mov.l	r0,@(320,gbr)
   e:	60 53       	mov	r5,r0
  10:	00 0b       	rts	
  12:	c2 51       	mov.l	r0,@(324,gbr)

00000014 <_slScrPosNbg2>:
  14:	60 43       	mov	r4,r0
  16:	c2 bb       	mov.l	r0,@(748,gbr)
  18:	60 53       	mov	r5,r0
  1a:	c2 bc       	mov.l	r0,@(752,gbr)
  1c:	44 29       	shlr16	r4
  1e:	20 4d       	xtrct	r4,r0
  20:	00 0b       	rts	
  22:	c2 54       	mov.l	r0,@(336,gbr)

00000024 <_slScrPosNbg3>:
  24:	60 43       	mov	r4,r0
  26:	c2 bd       	mov.l	r0,@(756,gbr)
  28:	60 53       	mov	r5,r0
  2a:	c2 be       	mov.l	r0,@(760,gbr)
  2c:	44 29       	shlr16	r4
  2e:	20 4d       	xtrct	r4,r0
  30:	00 0b       	rts	
  32:	c2 55       	mov.l	r0,@(340,gbr)
