
sglB087.o:     file format coff-sh


Disassembly of section SLPROG:

00000000 <_slLineScrollTable0>:
   0:	60 43       	mov	r4,r0
   2:	40 01       	shlr	r0
   4:	00 0b       	rts	
   6:	c2 58       	mov.l	r0,@(352,gbr)

00000008 <_slLineScrollTable1>:
   8:	60 43       	mov	r4,r0
   a:	40 01       	shlr	r0
   c:	00 0b       	rts	
   e:	c2 59       	mov.l	r0,@(356,gbr)

00000010 <_slVCellTable>:
  10:	60 43       	mov	r4,r0
  12:	40 01       	shlr	r0
  14:	00 0b       	rts	
  16:	c2 57       	mov.l	r0,@(348,gbr)
