#ifndef _BIN2C_HEADER_0CFF_4DAC_5FCE_1A34_
#define _BIN2C_HEADER_0CFF_4DAC_5FCE_1A34_

/* generated by bin2c from file ..\lib\sclib_4d_stub.bin */
#define SCLIB_4D_STUB_BIN_SIZ 77300
extern const unsigned char sclib_4d_stub_bin_dat[];

#endif // _BIN2C_HEADER_0CFF_4DAC_5FCE_1A34_
